apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-new
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-new
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e97a925086fbae93
    volumeAttributes:
      encryptInTransit: "true"

